title: "Sascha Essl"
description: "Notes on translation, periodicals, and research"

theme: minima

url: "https://saschaessl.github.io"
baseurl: ""

header_pages:
  - index.md
  - about.md
  - blog.md
